// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Auto_complete_server
{
    public partial class Cities
    {
        public string Name { get; set; }
        public string Country { get; set; }
        public string Subcountry { get; set; }
        public int Geonameid { get; set; }
    }
}