// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Auto_complete_server
{
    public partial class GetCitiesResult
    {
        public string name { get; set; }
        public string country { get; set; }
        public string subcountry { get; set; }
        public int geonameid { get; set; }
    }
}
